---
title: "Vis I"
author: "Maya Krishnamoorthy"
date: "2024-09-26"
output: github_document
---

```{r setup, message=FALSE, echo=FALSE}
library(tidyverse)
library(ggplot2)
```

Import the weather data.

``` {r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

Making our first plot!

``` {r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```

``` {r}
ggp_weather_scatterplot = 
  weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()

ggp_weather_scatterplot

```


## Fancier scatterplots!

``` {r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color=name), alpha = .3, size = .8) +
  geom_smooth(se = FALSE)
```

``` {r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)
```

Let's make a somewhat more interesting scatterplot.

``` {r}
weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name, size = prcp)) +
  geom_point() +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)
```


#### Learning assessment

``` {r}
weather_df |> 
  filter(name == "CentralPark_NY") |> 
  mutate(
    tmax_fahr = tmax * (9 / 5) + 32,
    tmin_fahr = tmin * (9 / 5) + 32
  ) |> 
  ggplot(aes(x = tmin_fahr, y = tmax_fahr)) +
  geom_point() + 
  geom_smooth(method = "lm", se = FALSE)
```


## Small things

``` {r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = .3, size = .8) +
  geom_smooth(se = FALSE)
```


``` {r}
# Density plot
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_hex()
```


``` {r}
# in ggplot, creates a variable called "blue" rather than use the color "blue"
# move to geom_point and then it should be better
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(color = "blue")

```

## Univariiate plots

``` {r}
weather_df |> 
  ggplot(aes(x = tmin)) +
  geom_histogram()
```


``` {r}
# dodge puts the histograms next to each other instead of on top of each other
weather_df |> 
  ggplot(aes(x = tmin, fill = name)) +
  geom_histogram(position = "dodge")
```

How could I fix this? Using facet?

``` {r}
weather_df |> 
  ggplot(aes(x = tmin, fill = name)) +
  geom_histogram() + 
  facet_grid(. ~ name)
```


Maybe try a density plot?

``` {r}
weather_df |> 
  ggplot(aes(x = tmin, fill = name)) +
  geom_density(alpha = .3)
```

``` {r}
weather_df |> 
  ggplot(aes(x = name, y = tmin)) +
  geom_boxplot()
```

Violin plots!

``` {r}
weather_df |> 
  ggplot(aes(x = name, y = tmin, fill = name)) +
  geom_violin()
```

Ridge plot

``` {r}
#ggplot(weather_df, aes(x = tmax, y = name)) + 
 # geom_density_ridges(scale = .85)
```


#### Learning assessment
``` {r}
weather_df |> 
  ggplot(aes(x = prcp, fill = name)) +
  geom_histogram(binwidth = 100, position = "dodge")
```

``` {r}
weather_df |> 
  ggplot(aes(x = prcp, fill = name)) +
  geom_density(alpha = .3)

weather_df |> 
  filter(prcp > 10) |> 
  ggplot(aes(x = prcp, fill = name)) +
  geom_density(alpha = .3)
```

``` {r}
weather_df |> 
  ggplot(aes(y = prcp, x = name)) + 
  geom_boxplot() 
```

## Saving and embedding plots

Saving plots:
``` {r}
ggp_weather = 
  weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point()

ggsave("plots/ggp_weather.pdf", ggp_weather, width = 8, height = 6)
```

Embedding plots:
``` {r, fig.width = 6, fig.asp = .6}
weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point()
```

